# Generated by Django 2.1 on 2018-08-20 14:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Nima', max_length=200)),
                ('last_name', models.CharField(default='Mohamadian', max_length=200)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=6)),
                ('age', models.IntegerField(choices=[(6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31)], default=6)),
                ('password', models.CharField(default='1234', max_length=32)),
                ('referral_code', models.IntegerField(default=None)),
                ('location', models.CharField(default='تهران', max_length=32)),
                ('paid', models.BooleanField(default=False)),
                ('ip', models.GenericIPAddressField(default='192.168.1.1')),
                ('register_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('email', models.URLField(default='<django.db.models.fields.CharField>@<django.db.models.fields.CharField>.com', max_length=36)),
                ('put_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
